### ISSUE TITLE
Replace beta.meower.org with this repo

### ISSUE THREAD

**Issue by JoshAtticus** [JoshAtticus/Meower-Beta-Hosted#1]
Replace the existing beta.meower.org project (which appears to just be a rehost of the current beta 5), with this repo, which contains the beta 6 development preview. I'll also add a button allowing users who may be looking for beta 5 to visit beta 5 when I get the time to re-write the whole website.

**Comment by JoshAtticus** [comment]
Just realised I need to do some big changes first, like putting the scripts on the same website to bypass cross-origin.

**Comment by JoshAtticus** [comment]
Just realised I need to do some big changes first, like putting the scripts on the same website to bypass cross-origin.

**Comment by tnix100** [comment]
Btw this repo shouldn't exist, there should just be a branch on the main repo for this. I will delete the repo after you see this comment.

**Comment by JoshAtticus** [comment]
> Btw this repo shouldn't exist, there should just be a branch on the main repo for this. I will delete the repo after you see this comment.

I’d like to keep this repo, so I transferred it to my account.
Also, while there is a branch, there is no hosted beta 6 instance, you must do it yourself. This repo aimed to change that.

**Comment by tnix100** [comment]
> Also, while there is a branch, there is no hosted beta 6 instance, you must do it yourself. This repo aimed to change that.
Once Beta 6 is ready enough to go to the beta branch, it will.

**Comment by JoshAtticus** [comment]
> > Also, while there is a branch, there is no hosted beta 6 instance, you must do it yourself. This repo aimed to change that.
> 
> Once Beta 6 is ready enough to go to the beta branch, it will.
> 
> 

Ok, well I'd also like to keep this repo as it stores historical betas.
